import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Input, Button, Checkbox, List } from "antd";

export default function Home() {
  const [ToDoItem, setToDoItem] = useState("");
  const [AllToDoList, setAllToDoList] = useState(null);
  const [id, setId] = useState("");

  function AllTodo() {
    fetch("/api/get-all-todo-list")
      .then((res) => res.json())
      .then((res) => {
        // console.log(res);
        setAllToDoList(res.todos.rows);
      });
  }

  useEffect(() => {
    AllTodo();
  }, []);

  function addTodoItem(ToDoItem) {
    fetch(`/api/add-todo-item?ToDoItem=${ToDoItem}`)
      .then((res) => res.json())
      .then((res) => {
        // console.log(res);
        AllTodo();
      });
    setToDoItem("");
  }

  function changeStatus(id, status) {
    fetch(`/api/change-status?id=${id}&status=${!status}`)
      .then((response) => response.json())
      .then((result) => {
        // console.log(result);
        AllTodo();
      });
  }

  function deleteAllTodos() {
    fetch("/api/delete-all-todos")
      .then((res) => res.json())
      .then((res) => {
        // console.log(res);
        setAllToDoList(null);
      });
  }

  function deleteOneTodo(id) {
    fetch(`/api/delete-one-todo?id=${id}`)
      .then((res) => res.json())
      .then((res) => {
        // console.log(res);
        AllTodo();
      });
    setId("");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ textAlign: "center" }}>
        <h1>Todo List</h1>
        <div>
          <Input
            type="text"
            placeholder="Enter a ToDo name"
            style={{ width: "20%", marginBottom: "7px", marginRight: "5px" }}
            value={ToDoItem}
            onChange={(e) => setToDoItem(e.target.value)}
          />
          <Button type="primary" onClick={() => addTodoItem(ToDoItem)}>
            Add ToDo Item
          </Button>
        </div>
        <div>
          <Input
            type="text"
            placeholder="Enter an ID"
            style={{
              width: "20%",
              marginTop: "7px",
              marginRight: "5px",
              marginBottom: "50px",
            }}
            value={id}
            onChange={(e) => setId(e.target.value)}
          />
          <Button type="primary" onClick={() => deleteOneTodo(id)}>
            Delete ToDo Item
          </Button>
        </div>
        <List
          style={{
            width: "50%",
            margin: "0 auto",
          }}
        >
          {AllToDoList?.map((todo, index) => (
            <List.Item key={index}>
              <span
                style={
                  todo.status === true
                    ? { textDecoration: "line-through" }
                    : { textDecoration: "none" }
                }
              >
                №{todo.id + ". "}
                {" " + todo.todo}
              </span>
              <Checkbox
                type="checkbox"
                checked={todo.status}
                readOnly
                onClick={() => changeStatus(todo.id, todo.status)}
              />
            </List.Item>
          ))}
        </List>
        <div>
          <Button
            type="primary"
            style={{ marginBottom: "50px", marginTop: "50px" }}
            onClick={() => deleteAllTodos()}
          >
            Delete All ToDo Items
          </Button>
        </div>
      </main>
    </>
  );
}
